import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Counter from "./component/Counter";
import { store } from "./Redux/store";
import { Provider } from "react-redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by Create Next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider store={store}>
          
          <Counter />
          
          {children}
        
        </Provider>
      
      </body>
    </html>
  );
}